version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
    #   - restore_cache:
    #       key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
    #   - save_cache:
    #       key: dependency-cache-{{ checksum "package-lock.json" }}
    #       paths:
    #         - ~/.cache/node_modules
    #         - ./node_modules
    #   - run:
    #       name: angular-build
    #       command: npm run build-prod
      - run:
          name: angular-test
          command: npm run test:single-run
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      # - run:
      #     name: angular-lint
      #     command: npm lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      # - store_artifacts:
      #     path: tslint.xml
      #     prefix: lint