version: 2
containerInfo:
  env:
    - DISPLAY=:99
    - CHROME_BIN=/usr/bin/google-chrome
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: maxatverblio/angular-test:0.0.1
    steps:
      - checkout
      - run: echo "Running angular test suite with $NODE_VERSION"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/node_modules
            - ./node_modules
      - run:
          name: angular-test
          command: npm run test:single-run
    #   - store_test_results:
    #       path: test-results.xml
    #   - store_artifacts:
    #       path: test-results.xml
    #       prefix: tests
      # - run:
      #     name: angular-lint
      #     command: npm lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      # - store_artifacts:
      #     path: tslint.xml
      #     prefix: lint